import datetime

EXPECTED_DICT_1040179875 = {
    "cpf": "60750197820",
    "nome": "EPIFANIO SCARDELATTO JUNIOR",
    "dt_nascimento": datetime.date(1952, 11, 20),
    "identidade": "00066048709",
    "genero": "MASCULINO",
    "codigo_banco": "104",
    "nome_banco": "CAIXA",
    "codigo_agencia": "0347",
    "nome_agencia": "SAO CAETANO DO SUL",
    "endereco_agencia": "RUA RIO GRANDE DO SUL, 436",
    "uf_agencia": "SP",
    "orgao_pagador": 265427,
    "tipo_pagamento": "CONTA CORRENTE",
    "numero_pagamento": "0000018436",
    "matricula_id": "1040179875",
    "situacao": "ATIVO    - ORIGEM PA",
    "nit": "10397865632",
    "codigo_matricula": "21",
    "descricao_matricula": "PENSAO POR MORTE PREVIDENCIARIA",
    "dib": datetime.date(1996, 7, 15),
    "valor_matricula": 1039.0,
    "representante_legal": False,
    "pensao_alimenticia": False,
    "bloqueio_emprestimo": False,
    "permite_emprestimo": True,
    "competencia": None,
    "margem_consignavel": None,
    "margem_emprestimo": None,
    "quantidade_emprestimo": None,
    "real_time": False,
    "possui_cartao": None,
    "margem_cartao": None
}
