import datetime

EXPECTED_DICT_5149392886 = {
    "cpf": "13198416515",
    "nome": "JOSE LUIZ DOS SANTOS SILVA",
    "dt_nascimento": datetime.date(1956, 2, 29),
    "identidade": "00000871843",
    "genero": "MASCULINO",
    "codigo_banco": "341",
    "nome_banco": "ITAU",
    "codigo_agencia": "6439",
    "nome_agencia": "SALVADOR - EXTRA ROTULA",
    "endereco_agencia": "AVENIDA BARROS REIS, 1400",
    "uf_agencia": "BA",
    "orgao_pagador": 647601,
    "tipo_pagamento": "CONTA CORRENTE",
    "numero_pagamento": "0000027985",
    "matricula_id": "5149392886",
    "situacao": "ATIVO",
    "nit": "10792120660",
    "codigo_matricula": "32",
    "descricao_matricula": "APOSENTADORIA POR INVALIDEZ PREVIDENCIARIA",
    "dib": datetime.date(2005, 10, 4),
    "valor_matricula": 3843.01,
    "representante_legal": False,
    "pensao_alimenticia": False,
    "bloqueio_emprestimo": False,
    "permite_emprestimo": True,
    "competencia": None,
    "margem_consignavel": None,
    "margem_emprestimo": None,
    "quantidade_emprestimo": None,
    "real_time": False,
    "possui_cartao": None,
    "margem_cartao": None
}
