import datetime

EXPECTED_DICT_5466201169 = {
    "cpf": "02149518805",
    "nome": "KARIN AGARI JORGENSEN DE CAMARGO",
    "dt_nascimento": datetime.date(1961, 4, 13),
    "identidade": "00064068304",
    'is_active': True,
    "genero": "FEMININO",
    "codigo_banco": "001",
    "nome_banco": "BRASIL",
    "codigo_agencia": "2962",
    "nome_agencia": "AVENIDA FARIA LIMA-SAO PAULO,SP",
    "endereco_agencia": "AV. BRIGADEIRO FARIA LIMA, 1732",
    "uf_agencia": "SP",
    "orgao_pagador": 289238,
    "tipo_pagamento": "CONTA CORRENTE",
    "numero_pagamento": "0004601459",
    "matricula_id": "5466201169",
    "situacao": "ATIVO",
    "nit": "12009267755",
    "codigo_matricula": "32",
    "descricao_matricula": "APOSENTADORIA POR INVALIDEZ PREVIDENCIARIA",
    "dib": datetime.date(2011, 6, 14),
    "valor_matricula": 5170.93,
    "representante_legal": False,
    "pensao_alimenticia": False,
    "bloqueio_emprestimo": False,
    "permite_emprestimo": True,
    "competencia": datetime.date(2020, 1, datetime.date.today().day),
    "margem_consignavel": 5170.93,
    "margem_emprestimo": 30.59,
    "quantidade_emprestimo": 7,
    "real_time": False,
    "possui_cartao": True,
    "margem_cartao": 24.14
}
