# Generated by Django 3.0.3 on 2021-05-24 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Está ativo')),
                ('cpf', models.CharField(max_length=255, verbose_name='CPF')),
                ('matricula', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Matrícula')),
                ('inserted_by_cpf_api', models.BooleanField(default=False, verbose_name='Inserido por API de CPF')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
            },
        ),
        migrations.CreateModel(
            name='MatriculaDetalhada',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Está ativo')),
                ('cpf', models.CharField(max_length=255, null=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=255, null=True, verbose_name='Nome')),
                ('dt_nascimento', models.DateField(null=True, verbose_name='Data Nascimento')),
                ('identidade', models.CharField(max_length=255, null=True, verbose_name='Numero Identidade')),
                ('genero', models.CharField(max_length=255, null=True, verbose_name='Genero')),
                ('codigo_banco', models.CharField(max_length=255, null=True, verbose_name='Código Banco')),
                ('nome_banco', models.CharField(max_length=255, null=True, verbose_name='Nome Banco')),
                ('codigo_agencia', models.CharField(max_length=255, null=True, verbose_name='Codigo Agencia')),
                ('nome_agencia', models.CharField(max_length=255, null=True, verbose_name='Nome Agencia')),
                ('endereco_agencia', models.CharField(max_length=255, null=True, verbose_name='Endereco Agencia')),
                ('uf_agencia', models.CharField(max_length=255, null=True, verbose_name='UF Agencia')),
                ('orgao_pagador', models.IntegerField(null=True, verbose_name='Orgao Pagador')),
                ('tipo_pagamento', models.CharField(max_length=255, null=True, verbose_name='Tipo Pagamento')),
                ('numero_pagamento', models.CharField(max_length=255, null=True, verbose_name='Numero Pagamento')),
                ('matricula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data_consig.Matricula')),
                ('situacao', models.CharField(max_length=255, null=True, verbose_name='Situacao Matricula')),
                ('nit', models.CharField(max_length=255, null=True, verbose_name='NIT')),
                ('codigo_matricula', models.CharField(max_length=255, null=True, verbose_name='Codigo Matricula')),
                ('descricao_matricula', models.CharField(max_length=255, null=True, verbose_name='Descricao Matricula')),
                ('dib', models.DateField(null=True, verbose_name='DIB')),
                ('valor_matricula', models.FloatField(null=True, verbose_name='Valor Matricula')),
                ('representante_legal', models.BooleanField(null=True, verbose_name='Representante legal')),
                ('pensao_alimenticia', models.BooleanField(null=True, verbose_name='Pensao Alimenticia')),
                ('bloqueio_emprestimo', models.BooleanField(null=True, verbose_name='Bloqueio Emprestimo')),
                ('permite_emprestimo', models.BooleanField(null=True, verbose_name='Permite Emprestimo')),
                ('competencia', models.DateField(null=True, verbose_name='Competencia')),
                ('margem_consignavel', models.FloatField(null=True, verbose_name='Margem Consignavel')),
                ('margem_emprestimo', models.FloatField(null=True, verbose_name='Margem Emprestimo')),
                ('quantidade_emprestimo', models.IntegerField(null=True, verbose_name='Quantidade Emprestimo')),
                ('possui_cartao', models.BooleanField(null=True, verbose_name='Possui Cartao')),
                ('margem_cartao', models.FloatField(null=True, verbose_name='Margem Cartao')),
                ('real_time', models.BooleanField(default=False, verbose_name='Real Time')),
            ],
            options={
                'verbose_name': 'Matrícula Detalhada',
                'verbose_name_plural': 'Matrículas Detalhadas',
            },
        ),
        migrations.CreateModel(
            name='ContratoEmprestimo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Está ativo')),
                ('contrato', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Numero Contrato')),
                ('codigo_emprestimo', models.CharField(max_length=255, null=True, verbose_name='Codigo Emprestimo')),
                ('descricao_emprestimo', models.CharField(max_length=255, null=True, verbose_name='Descricao Emprestimo')),
                ('codigo_banco', models.CharField(max_length=255, null=True, verbose_name='Codigo Banco')),
                ('nome_banco', models.CharField(max_length=255, null=True, verbose_name='Nome Banco')),
                ('data_inicio', models.DateField(null=True, verbose_name='Data Inicio Contrato')),
                ('competencia_inicio_desconto', models.DateField(null=True, verbose_name='Competencia Inicio Desconto')),
                ('competencia_fim_desconto', models.DateField(null=True, verbose_name='Competencia Fim Desconto')),
                ('data_inclusao', models.DateField(null=True, verbose_name='Data Inclusao')),
                ('situacao', models.CharField(max_length=255, null=True, verbose_name='Situacao Contrato')),
                ('excluido_aps', models.BooleanField(null=True, verbose_name='Excluido APS')),
                ('excluido_banco', models.BooleanField(null=True, verbose_name='Excluido Banco')),
                ('valor_emprestimo', models.FloatField(null=True, verbose_name='Valor Emprestimo')),
                ('valor_parcela', models.FloatField(null=True, verbose_name='Valor Parcela')),
                ('quantidade_parcelas', models.IntegerField(null=True, verbose_name='Quantidade Parcelas')),
                ('parcelas_aberto', models.IntegerField(null=True, verbose_name='Parcelas em Aberto')),
                ('saldo', models.FloatField(null=True, verbose_name='Saldo para Quitação')),
                ('taxa', models.FloatField(null=True, verbose_name='Taxa')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_consig.MatriculaDetalhada')),
            ],
            options={
                'verbose_name': 'Contrato de Empréstimo ',
                'verbose_name_plural': 'Contratos de Empréstimos',
            },
        ),
        migrations.CreateModel(
            name='ContratoCartao',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Está ativo')),
                ('contrato', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Numero Contrato')),
                ('codigo_cartao', models.CharField(max_length=255, null=True, verbose_name='Codigo Cartao')),
                ('descricao_cartao', models.CharField(max_length=255, null=True, verbose_name='Descricao Cartao')),
                ('codigo_banco', models.CharField(max_length=255, null=True, verbose_name='Codigo Banco')),
                ('nome_banco', models.CharField(max_length=255, null=True, verbose_name='Nome Banco')),
                ('inicio_contrato', models.DateField(null=True, verbose_name='Inicio Contrato')),
                ('inclusao_contrato', models.DateField(null=True, verbose_name='Inclusao Contrato')),
                ('situacao', models.CharField(max_length=255, null=True, verbose_name='Situacao Contrato')),
                ('excluido_aps', models.BooleanField(null=True, verbose_name='Excluido APS')),
                ('excluido_banco', models.BooleanField(null=True, verbose_name='Excluido Banco')),
                ('limite_cartao', models.FloatField(null=True, verbose_name='Limite Cartao')),
                ('valor_reservado', models.FloatField(null=True, verbose_name='Valor Reservado')),
                ('matricula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_consig.MatriculaDetalhada')),
            ],
            options={
                'verbose_name': 'Contrato de Cartão',
                'verbose_name_plural': 'Contratos de Cartões',
            },
        ),
    ]
