# Generated by Django 3.0.3 on 2021-05-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='perfil',
            field=models.CharField(choices=[('Comercial', 'Comercial'), ('Esteira', 'Esteira'), ('Telefone', 'Telefone')], max_length=12),
        ),
    ]
