# Generated by Django 3.0.3 on 2021-05-26 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bancos', '0001_initial'),
        ('produto', '0002_auto_20210526_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coeficiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.SmallIntegerField(blank=True, null=True)),
                ('tabela', models.CharField(blank=True, max_length=255, null=True)),
                ('coeficiente', models.CharField(blank=True, max_length=20, null=True)),
                ('comissao', models.CharField(blank=True, max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancos.Banco')),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.Produto')),
            ],
        ),
    ]
