# Generated by Django 3.0.3 on 2021-05-26 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('convenio', '0001_initial'),
        ('status', '0001_initial'),
        ('data_consig', '0001_initial'),
        ('bancos', '0001_initial'),
        ('coeficiente', '0001_initial'),
        ('produto', '0002_auto_20210526_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_bruto', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('valor_liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('saldo_devedor', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('informacao', models.CharField(blank=True, max_length=200, null=True)),
                ('previsao_saldo', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id_banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancos.Banco')),
                ('id_banco_sacado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banco_sacado', to='bancos.Banco')),
                ('id_coeficiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coeficiente.Coeficiente')),
                ('id_convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convenio.Convenio')),
                ('id_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_consig.Matricula')),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.Produto')),
                ('id_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='status.Status')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Usuario')),
            ],
        ),
    ]
