import datetime

today_day = datetime.date.today().day

EXPECTED_DICT_706240146 = [
    {
        'contrato': '608318828',
        'matricula_id': '0706240146',
        'codigo_emprestimo': 98,
        'descricao_emprestimo': 'Empréstimo por Consignação',
        'codigo_banco': '029',
        'nome_banco': 'ITAU CONSIGNADO',
        'data_inicio': datetime.date(2019, 12, 19),
        'competencia_inicio_desconto': datetime.date(2020, 1, today_day),
        'competencia_fim_desconto': datetime.date(2025, 12, today_day),
        'data_inclusao': datetime.date(2019, 12, 19),
        'situacao': 'Ativo',
        'excluido_aps': False,
        'excluido_banco': False,
        'is_active': True,
        'valor_emprestimo': 6250.0,
        'valor_parcela': 176.0,
        'quantidade_parcelas': 72,
        'parcelas_aberto': 72,
        'saldo': 6358.3,
        'taxa': 2.25
    },
    {
        'contrato': '185473494',
        'matricula_id': '0706240146',
        'codigo_emprestimo': 98,
        'descricao_emprestimo': 'Empréstimo por Consignação',
        'codigo_banco': '955',
        'nome_banco': 'OLE CONSIGNADO',
        'data_inicio': datetime.date(2020, 1, 21),
        'competencia_inicio_desconto': datetime.date(2020, 2, today_day)
        if today_day < 31 else datetime.date(2020, 2, today_day - 2),
        'competencia_fim_desconto': datetime.date(2026, 1, today_day),
        'data_inclusao': datetime.date(2020, 1, 21),
        'situacao': 'Ativo',
        'excluido_aps': False,
        'excluido_banco': False,
        'is_active': True,
        'valor_emprestimo': 7029.44,
        'valor_parcela': 198.3,
        'quantidade_parcelas': 72,
        'parcelas_aberto': 72,
        'saldo': 7151.25,
        'taxa': 2.25
    },
    {
        'contrato': '603404309',
        'matricula_id': '0706240146',
        'codigo_emprestimo': 98,
        'descricao_emprestimo': 'Empréstimo por Consignação',
        'codigo_banco': '029',
        'nome_banco': 'ITAU CONSIGNADO',
        'data_inicio': datetime.date(2019, 11, 4),
        'competencia_inicio_desconto': datetime.date(2019, 12, today_day),
        'competencia_fim_desconto': datetime.date(2025, 11, today_day)
        if today_day < 31 else datetime.date(2025, 11, today_day - 1),
        'data_inclusao': datetime.date(2019, 11, 4),
        'situacao': 'Ativo',
        'excluido_aps': False,
        'excluido_banco': False,
        'is_active': True,
        'valor_emprestimo': 5795.28,
        'valor_parcela': 164.47,
        'quantidade_parcelas': 72,
        'parcelas_aberto': 70,
        'saldo': 5837.0,
        'taxa': 2.28
    },
    {
        'contrato': '813243754',
        'matricula_id': '0706240146',
        'codigo_emprestimo': 98,
        'descricao_emprestimo': 'Empréstimo por Consignação',
        'codigo_banco': '394',
        'nome_banco': 'BRAD. FINANCIAM',
        'data_inicio': datetime.date(2019, 11, 5),
        'competencia_inicio_desconto': datetime.date(2019, 12, today_day),
        'competencia_fim_desconto': datetime.date(2025, 11, today_day)
        if today_day < 31 else datetime.date(2025, 11, today_day - 1),
        'data_inclusao': datetime.date(2019, 11, 5),
        'situacao': 'Ativo',
        'excluido_aps': False,
        'excluido_banco': False,
        'is_active': True,
        'valor_emprestimo': 51596.56,
        'valor_parcela': 1130.0,
        'quantidade_parcelas': 72,
        'parcelas_aberto': 71,
        'saldo': 51458.44,
        'taxa': 1.36
    },
    {
        'contrato': '58002443410-331',
        'matricula_id': '0706240146',
        'codigo_emprestimo': 98,
        'descricao_emprestimo': 'Empréstimo por Consignação',
        'codigo_banco': '254',
        'nome_banco': 'PARANA BANCO',
        'data_inicio': datetime.date(2019, 12, 29),
        'competencia_inicio_desconto': datetime.date(2020, 1, today_day),
        'competencia_fim_desconto': datetime.date(2025, 12, today_day),
        'data_inclusao': datetime.date(2019, 12, 29),
        'situacao': 'Ativo',
        'excluido_aps': False,
        'excluido_banco': False,
        'is_active': True,
        'valor_emprestimo': 32235.5,
        'valor_parcela': 904.25,
        'quantidade_parcelas': 72,
        'parcelas_aberto': 72,
        'saldo': 32785.77,
        'taxa': 2.23
    },
    {
        'contrato': '601901264',
        'matricula_id': '0706240146',
        'codigo_emprestimo': 98,
        'descricao_emprestimo': 'Empréstimo por Consignação',
        'codigo_banco': '029',
        'nome_banco': 'ITAU CONSIGNADO',
        'data_inicio': datetime.date(2019, 10, 23),
        'competencia_inicio_desconto': datetime.date(2019, 11, today_day),
        'competencia_fim_desconto': datetime.date(2025, 10, today_day),
        'data_inclusao': datetime.date(2019, 10, 23),
        'situacao': 'Ativo',
        'excluido_aps': False,
        'excluido_banco': False,
        'is_active': True,
        'valor_emprestimo': 5846.7,
        'valor_parcela': 164.0,
        'quantidade_parcelas': 72,
        'parcelas_aberto': 70,
        'saldo': 5883.28,
        'taxa': 2.23
    },
    {
        'contrato': '25-50509/19015',
        'matricula_id': '0706240146',
        'codigo_emprestimo': 98,
        'descricao_emprestimo': 'Empréstimo por Consignação',
        'codigo_banco': '901',
        'nome_banco': 'CCB BRASIL',
        'data_inicio': datetime.date(2019, 10, 5),
        'competencia_inicio_desconto': datetime.date(2019, 11, today_day),
        'competencia_fim_desconto': datetime.date(2025, 5, today_day),
        'data_inclusao': datetime.date(2019, 10, 5),
        'situacao': 'Ativo',
        'excluido_aps': False,
        'excluido_banco': False,
        'is_active': True,
        'valor_emprestimo': 33056.36,
        'valor_parcela': 747.11,
        'quantidade_parcelas': 67,
        'parcelas_aberto': 65,
        'saldo': 32567.86,
        'taxa': 1.32
    },
    {
        'contrato': '0005416412',
        'matricula_id': '0706240146',
        'codigo_emprestimo': 98,
        'descricao_emprestimo': 'Empréstimo por Consignação',
        'codigo_banco': '935',
        'nome_banco': 'FACTA',
        'data_inicio': datetime.date(2019, 9, 19),
        'competencia_inicio_desconto': datetime.date(2019, 10, today_day),
        'competencia_fim_desconto': datetime.date(2025, 9, today_day)
        if today_day < 31 else datetime.date(2025, 9, today_day - 1),
        'data_inclusao': datetime.date(2019, 9, 19),
        'situacao': 'Ativo',
        'excluido_aps': False,
        'excluido_banco': False,
        'is_active': True,
        'valor_emprestimo': 8280.62,
        'valor_parcela': 179.15,
        'quantidade_parcelas': 72,
        'parcelas_aberto': 69,
        'saldo': 8113.94,
        'taxa': 1.33
    },
    {
        'contrato': '55-6469741/19',
        'matricula_id': '0706240146',
        'codigo_emprestimo': 98,
        'descricao_emprestimo': 'Empréstimo por Consignação',
        'codigo_banco': '707',
        'nome_banco': 'DAYCOVAL',
        'data_inicio': datetime.date(2019, 8, 9),
        'competencia_inicio_desconto': datetime.date(2019, 9, today_day)
        if today_day < 31 else datetime.date(2019, 9, today_day - 1),
        'competencia_fim_desconto': datetime.date(2025, 8, today_day),
        'data_inclusao': datetime.date(2019, 8, 9),
        'situacao': 'Ativo',
        'excluido_aps': False,
        'excluido_banco': False,
        'is_active': True,
        'valor_emprestimo': 12570.68,
        'valor_parcela': 286.02,
        'quantidade_parcelas': 72,
        'parcelas_aberto': 68,
        'saldo': 12264.68,
        'taxa': 1.49
    }
]
